<?php
/**
 * This file is part of Jbh_ConnectAs for Magento.
 *
 * @license All rights reserved
 * @author Jacques Bodin-Hullin <@jacquesbh> <j.bodinhullin@monsieurbiz.com>
 * @category Jbh
 * @package Jbh_ConnectAs
 * @copyright Copyright (c) 2014 Monsieur Biz (http://monsieurbiz.com/)
 */
/* @var $this Jbh_ConnectAs_Block_Notice */
?>
<?php if ($value = $this->helper('jbh_connectas')->getCookieValue()): ?>
<div style="background: #F9B933; color: black; font-weight: bold; text-align: center; padding: 5px 0;">
    <?php echo $this->__("You're connected as <em>%s</em>.", $value); ?>
</div>
<?php endif; ?>
